#!/usr/bin/env bash

set -e

NAMESPACE_ATOMIX_RUNTIME="kube-system"

#"$SNAP/microk8s-enable.wrapper" helm3
HELM="$SNAP/microk8s-helm3.wrapper"

echo "Installing atomix-runtime"

$HELM repo add --force-update atomix https://charts.atomix.io
$HELM upgrade -i -n $NAMESPACE_ATOMIX_RUNTIME atomix/atomix-runtime

echo "Aromix-runtime is installed"
